services:

  license-server-rs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: debug
    env_file:
      - .env
    ports:
      - "8089:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

