version: '3.1'

services:

  gui:
    build:
      context: .
      dockerfile: Dockerfile-gui
    restart: unless-stopped
    ports:
      - "80:8080"
      - "4200:8080"
    networks:
      - frontend

networks:
  frontend:
