services:

  traefik:
    image: traefik:v3.2
    ports:
      - "80:80"
      - "8083:8080" # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - license-backend
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.docker.localhost`)

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 500
    ports:
      - "5432:5432"
    networks:
      - license-backend
    volumes:
      - ./docker-compose/postgres/data/logs:/var/lib/postgresql/data
      - ./docker-compose/postgres/init:/docker-entrypoint-initdb.d/:ro

  mailhog:
    image: mailhog/mailhog
    restart: unless-stopped
    logging:
      driver: none
    ports:
      - "8025:8025"  # Web interface
      - "1025:1025"  # SMTP server
    networks:
      - license-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailhog.rule=PathPrefix(`/mail`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"


  keycloak:
    image: bitnami/keycloak:${KC_VERSION}
    restart: unless-stopped
    depends_on:
      mailhog:
        condition: service_started
      traefik:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN_USER: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: ${PG_DATABASE}
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: ${PG_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${PG_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: http://localhost/auth
      HTTP_RELATIVE_PATH: /auth
      KC_HTTP_RELATIVE_PATH: /auth
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - './docker-compose/keycloak/themes:/opt/bitnami/keycloak/themes'
      - './docker-compose/exports:/keycloak-transfer'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    ports:
      - "8081:8080"
      - "9090:9090"
    networks:
      - license-backend
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:8080/auth/realms" ]
      interval: 1s
      timeout: 1s
      retries: 1000
      start_period: 5s

  license-server:
    build:
      context: .
      dockerfile: Dockerfile-spring
    restart: unless-stopped
    environment:
      - LICENSE_GENERATION_MULTIPLIER=50
      - LICENSE_PRIVATE_KEY_FILE=license-key-private.der
      - LICENSE_SIGNATURE_LENGTH=150
      - LICENSE_ROLE_PREFIX=ROLE_
      - LICENSE_RATE_LIMIT=45
      - LICENSE_RATE_LIMIT_CACHE_EXPIRATION=1
      - SERVER_SERVLET_CONTEXT_PATH=/license/api/v1
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health
      - LOGGING_FILE_PATH=./logs
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=http://localhost/auth/realms/license
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://host.docker.internal:80/auth/realms/license/protocol/openid-connect/certs
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${PG_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${PG_USER}
      - SPRING_DATASOURCE_PASSWORD=${PG_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DLL_AUTO=update
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - license-backend
    volumes:
      - ./docker-compose/license-server/logs:/logs
      - ./docker-compose/license-server/key:/home/app/key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.license-server.rule=PathPrefix(`/license`)"
      - "traefik.http.services.license-server.loadbalancer.server.port=8080"

networks:
  license-backend:

