services:

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 500
    ports:
      - "543:5432"
    networks:
      - keycloak-network
    volumes:
      - ./keycloak/pg-data:/var/lib/postgresql/data

  keycloak:
    image: bitnami/keycloak:${KEYCLOAK_VERSION}
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: ${PG_DATABASE}
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: ${PG_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${PG_PASSWORD}
      KEYCLOAK_MIGRATION_ACTION: import
      KEYCLOAK_MIGRATION_PROVIDER: singleFile
      KEYCLOAK_MIGRATION_FILE: /keycloak-transfer/license-realm.json
      KEYCLOAK_MIGRATION_STRATEGY: OVERWRITE_EXISTING
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080/realms/master"]
      interval: 30s
      timeout: 5s
      retries: 500
    ports:
      - "8082:8080"
      - "8787:8787" # debug port
    networks:
      - keycloak-network
    volumes:
      - './keycloak/themes:/opt/bitnami/keycloak/themes'
      - './keycloak/exports:/keycloak-transfer'
      - './keycloak/auto-import:/opt/bitnami/keycloak/data/import'

networks:
  keycloak-network:
