services:
  traefik:
    image: traefik:v3.2
    ports:
      - "80:80"
      - "8083:8080" # Traefik Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - keycloak
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --providers.docker.defaultrule=Host(`{{ index .Labels "com.docker.compose.service" }}.docker.localhost`)

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - ./keycloak/pg-data:/var/lib/postgresql/data
    networks:
      - keycloak
    ports:
      - "543:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 500

  keycloak:
    image: bitnami/keycloak:${KEYCLOAK_VERSION}
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: ${PG_DATABASE}
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: ${PG_USER}
      KEYCLOAK_DATABASE_PASSWORD: ${PG_PASSWORD}
      KEYCLOAK_MIGRATION_ACTION: import
      KEYCLOAK_MIGRATION_PROVIDER: singleFile
      KEYCLOAK_MIGRATION_FILE: /keycloak-transfer/license-realm.json
      KEYCLOAK_MIGRATION_STRATEGY: OVERWRITE_EXISTING
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: http://localhost/auth
      HTTP_RELATIVE_PATH: /auth
      KC_HTTP_RELATIVE_PATH: /auth
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - './keycloak/themes:/opt/bitnami/keycloak/themes'
      - './keycloak/exports:/keycloak-transfer'
      - './keycloak/auto-import:/opt/bitnami/keycloak/data/import'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    ports:
      - "8081:8080"
      - "9090:9090"
    networks:
      - keycloak
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8080/auth/realms"]
      interval: 1s
      timeout: 1s
      retries: 1000
      start_period: 5s

networks:
  keycloak:
